baseURL = "http://example.org/clyde-example-app/"
languageCode = "en-us"
title = "Clyde Sample App"
theme = "clyde"
pygmentsUseClasses=true
publishDir = "docs"
relativeURLs = true
canonifyURLs = true


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
      
[params]
    #colors
    secondary = "#1E1F21"
    sidebar_bg = "#f6f6f8"
    sidebar_primary = "#1E1F21"
    primary = "#fff"
    accent = "#e3413a"
    grey200 = "#F9F9FA"
    grey600 = "#1E1F21"
    grey_head= "#EFEFF3"

    logo = "/default_button.png"

    home = "/docs/"
[outputs]
    section = ["HTML"]
    home = ["JSON", "HTML"]

[menu]
    [[menu.main]]
        identifier = "home"
        pre = "<i class='icon-home'></i>"
        name = "Home"
        url = "/"
        weight = -999
    [[menu.main]]
        identifier = "git"
        pre = "<i class='icon-github'></i>"
        name = "Github"
        url = "https://github.com/gewenyu99/clyde-example-app"
        weight = 1